FROM wordpress:6.5-apache
RUN apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*
COPY ../../wordpress/wp-temporal-cms /var/www/html/wp-content/plugins/wp-temporal-cms
RUN chown -R www-data:www-data /var/www/html/wp-content/plugins/wp-temporal-cms
